name: deploy-container

on:
  push:
    branches:
      -main
      paths:
      - 'container/**'

defaults:
    run:
        working-directoy: container  
jobs:     
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: yarn install
        - run: yarn build